import {
  JastipOrder,
  DriverPerformance,
  CustomerProfile,
  StoreMarket,
  TimeSLABreakdown,
  HourlyOrderPattern,
  FinancialOverview,
} from '@/types/jastip';

// ─── 1. DRIVERS / PERSONAL SHOPPERS DATA ──────────────────────────
export const INITIAL_DRIVERS: DriverPerformance[] = [
  {
    id: 'drv-01',
    name: 'Budi Santoso',
    phone: '0812-3456-7890',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    vehicle: 'Motor',
    licensePlate: 'B 4192 KDA',
    status: 'shopping',
    currentLocation: 'Pasar Tanah Abang Blok A',
    rating: 4.95,
    totalReviews: 248,
    ordersCompletedToday: 9,
    ordersCompletedMonth: 184,
    activeOrdersCount: 2,
    avgShoppingSpeedMins: 32,
    avgDeliverySpeedMins: 24,
    onTimeDeliveryRate: 98.2,
    todayCommission: 195000,
    cashFloatHeld: 1450000,
    recentDeliveries: [
      { orderId: 'JST-8921', store: 'Tanah Abang', customer: 'Siti Rahma', timeMins: 48, isOnTime: true, rating: 5 },
      { orderId: 'JST-8914', store: 'IKEA Alam Sutera', customer: 'Maya Anggraini', timeMins: 62, isOnTime: true, rating: 5 },
      { orderId: 'JST-8902', store: 'Pasar Baru', customer: 'Fajar Nugraha', timeMins: 41, isOnTime: true, rating: 5 },
    ],
  },
  {
    id: 'drv-02',
    name: 'Rian Pratama',
    phone: '0813-8877-2211',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    vehicle: 'Motor',
    licensePlate: 'B 6231 TZF',
    status: 'delivering',
    currentLocation: 'Menuju Tebet Timur (Sudirman)',
    rating: 4.88,
    totalReviews: 195,
    ordersCompletedToday: 8,
    ordersCompletedMonth: 162,
    activeOrdersCount: 1,
    avgShoppingSpeedMins: 38,
    avgDeliverySpeedMins: 28,
    onTimeDeliveryRate: 95.8,
    todayCommission: 172000,
    cashFloatHeld: 980000,
    recentDeliveries: [
      { orderId: 'JST-8925', store: 'Grand Indonesia', customer: 'Dewi Lestari', timeMins: 55, isOnTime: true, rating: 5 },
      { orderId: 'JST-8911', store: 'Pasar Mayestik', customer: 'Amanda Putri', timeMins: 45, isOnTime: true, rating: 4 },
    ],
  },
  {
    id: 'drv-03',
    name: 'Ahmad Fauzi',
    phone: '0857-1122-3344',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    vehicle: 'Mobil',
    licensePlate: 'B 1874 POX',
    status: 'shopping',
    currentLocation: 'IKEA Alam Sutera (Barang Bulky)',
    rating: 4.92,
    totalReviews: 310,
    ordersCompletedToday: 6,
    ordersCompletedMonth: 140,
    activeOrdersCount: 3,
    avgShoppingSpeedMins: 45,
    avgDeliverySpeedMins: 35,
    onTimeDeliveryRate: 96.5,
    todayCommission: 240000,
    cashFloatHeld: 3200000,
    recentDeliveries: [
      { orderId: 'JST-8919', store: 'IKEA Alam Sutera', customer: 'Bambang Kusuma', timeMins: 85, isOnTime: true, rating: 5 },
      { orderId: 'JST-8908', store: 'Mitra10 Fatmawati', customer: 'Hendra Gunawan', timeMins: 70, isOnTime: true, rating: 5 },
    ],
  },
  {
    id: 'drv-04',
    name: 'Dimas Wicaksono',
    phone: '0878-9988-7766',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80',
    vehicle: 'Motor',
    licensePlate: 'B 3099 BTR',
    status: 'standby',
    currentLocation: 'Hub Jakarta Selatan (Blok M)',
    rating: 4.79,
    totalReviews: 142,
    ordersCompletedToday: 7,
    ordersCompletedMonth: 135,
    activeOrdersCount: 0,
    avgShoppingSpeedMins: 42,
    avgDeliverySpeedMins: 31,
    onTimeDeliveryRate: 93.4,
    todayCommission: 145000,
    cashFloatHeld: 500000,
    recentDeliveries: [
      { orderId: 'JST-8917', store: 'Pasar Senen Kue Subuh', customer: 'Ratna Juwita', timeMins: 50, isOnTime: true, rating: 4 },
      { orderId: 'JST-8898', store: 'Kartika Sari Express', customer: 'Reza Pahlevi', timeMins: 65, isOnTime: false, rating: 4 },
    ],
  },
  {
    id: 'drv-05',
    name: 'Eko Wahyudi',
    phone: '0819-2233-4455',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    vehicle: 'Motor',
    licensePlate: 'B 5541 SGH',
    status: 'delivering',
    currentLocation: 'Menuju BSD City Sektor 1',
    rating: 4.96,
    totalReviews: 280,
    ordersCompletedToday: 10,
    ordersCompletedMonth: 210,
    activeOrdersCount: 1,
    avgShoppingSpeedMins: 29,
    avgDeliverySpeedMins: 22,
    onTimeDeliveryRate: 99.1,
    todayCommission: 210000,
    cashFloatHeld: 850000,
    recentDeliveries: [
      { orderId: 'JST-8924', store: 'Pasar Modern BSD', customer: 'Indah Permata', timeMins: 38, isOnTime: true, rating: 5 },
      { orderId: 'JST-8916', store: 'Sentra Oleh-oleh', customer: 'Wahyu Hidayat', timeMins: 40, isOnTime: true, rating: 5 },
    ],
  },
  {
    id: 'drv-06',
    name: 'Gita Danuarta',
    phone: '0821-6655-4433',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    vehicle: 'Motor',
    licensePlate: 'B 4412 NKL',
    status: 'off',
    currentLocation: 'Istirahat (Selesai Shift Siang)',
    rating: 4.85,
    totalReviews: 120,
    ordersCompletedToday: 5,
    ordersCompletedMonth: 98,
    activeOrdersCount: 0,
    avgShoppingSpeedMins: 36,
    avgDeliverySpeedMins: 29,
    onTimeDeliveryRate: 94.0,
    todayCommission: 110000,
    cashFloatHeld: 0,
    recentDeliveries: [
      { orderId: 'JST-8905', store: 'Pasar Santa', customer: 'Dian Sastro', timeMins: 52, isOnTime: true, rating: 5 },
    ],
  },
];

// ─── 2. STORES / MARKETS DATA ─────────────────────────────────────
export const INITIAL_STORES: StoreMarket[] = [
  {
    id: 'str-01',
    name: 'Pasar Tanah Abang (Blok A & B)',
    location: 'Jakarta Pusat',
    category: 'Fashion & Tekstil Grosir',
    totalOrders: 428,
    totalGMV: 64200000,
    fulfillmentRate: 97.4,
    avgShoppingMins: 38,
    popularItems: ['Gamis Rayon Premium', 'Kemeja Linen Oversize', 'Jilbab Paris Voal', 'Mukena Silk'],
  },
  {
    id: 'str-02',
    name: 'IKEA Alam Sutera & JGC',
    location: 'Tangerang / Jakarta Timur',
    category: 'Home & Living',
    totalOrders: 215,
    totalGMV: 48900000,
    fulfillmentRate: 98.8,
    avgShoppingMins: 52,
    popularItems: ['Raskog Trolley', 'Lerkil Cushion', 'Swedish Meatball Frozen', 'Pojk Bag'],
  },
  {
    id: 'str-03',
    name: 'Grand Indonesia (Sephora & Zara)',
    location: 'Jakarta Pusat',
    category: 'Beauty & Luxury Retail',
    totalOrders: 184,
    totalGMV: 39500000,
    fulfillmentRate: 95.2,
    avgShoppingMins: 34,
    popularItems: ['Rare Beauty Blush', 'Zara Eau De Parfum 100ml', 'The Body Shop Shower Gel'],
  },
  {
    id: 'str-04',
    name: 'Pasar Senen (Kue Subuh & Grosir)',
    location: 'Jakarta Pusat',
    category: 'Kuliner & Snack Tradisional',
    totalOrders: 310,
    totalGMV: 18600000,
    fulfillmentRate: 99.1,
    avgShoppingMins: 26,
    popularItems: ['Snack Box 50 Pcs', 'Lemper Ayam Spesial', 'Kue Sus Buah', 'Pastel Ragout'],
  },
  {
    id: 'str-05',
    name: 'Sentra Kuliner & Oleh-oleh Bandung',
    location: 'Bandung / Drop Point',
    category: 'Kuliner & Oleh-oleh Daerah',
    totalOrders: 265,
    totalGMV: 31800000,
    fulfillmentRate: 96.5,
    avgShoppingMins: 40,
    popularItems: ['Kartika Sari Pisang Bollen', 'Prima Rasa Brownies Panggang', 'Batagor Kingsley'],
  },
  {
    id: 'str-06',
    name: 'Pasar Mayestik',
    location: 'Jakarta Selatan',
    category: 'Kain & Crafting',
    totalOrders: 142,
    totalGMV: 22400000,
    fulfillmentRate: 94.0,
    avgShoppingMins: 45,
    popularItems: ['Kain Brokat Tile Mutiara', 'Songket Palembang Handmade', 'Kancing Vintage'],
  },
];

// ─── 3. CUSTOMERS DATA ───────────────────────────────────────────
export const INITIAL_CUSTOMERS: CustomerProfile[] = [
  {
    id: 'cst-01',
    name: 'Siti Rahmawati, S.E.',
    phone: '0812-9988-1122',
    email: 'siti.rahma@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    district: 'Jakarta Selatan (Kebayoran Baru)',
    tier: 'VIP',
    totalOrders: 38,
    totalSpent: 18450000,
    lastOrderDate: '2026-09-01',
    favoriteCategories: ['Fashion & Tekstil', 'Beauty & Luxury Retail'],
    favoriteStores: ['Pasar Tanah Abang', 'Grand Indonesia'],
    csatRating: 5.0,
    paymentPreference: 'QRIS',
  },
  {
    id: 'cst-02',
    name: 'dr. Maya Anggraini',
    phone: '0811-2233-4455',
    email: 'dr.maya@klinik.co.id',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    district: 'Tangerang Selatan (BSD City)',
    tier: 'VIP',
    totalOrders: 29,
    totalSpent: 14200000,
    lastOrderDate: '2026-09-01',
    favoriteCategories: ['Home & Living', 'Kuliner & Snack'],
    favoriteStores: ['IKEA Alam Sutera', 'Sentra Kuliner Bandung'],
    csatRating: 4.9,
    paymentPreference: 'Bank Transfer',
  },
  {
    id: 'cst-03',
    name: 'Amanda Putri Maharani',
    phone: '0817-5544-3322',
    email: 'amanda.mhrn@outlook.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    district: 'Jakarta Selatan (Cilandak)',
    tier: 'VIP',
    totalOrders: 24,
    totalSpent: 11900000,
    lastOrderDate: '2026-08-31',
    favoriteCategories: ['Kain & Crafting', 'Fashion'],
    favoriteStores: ['Pasar Mayestik', 'Pasar Tanah Abang'],
    csatRating: 5.0,
    paymentPreference: 'QRIS',
  },
  {
    id: 'cst-04',
    name: 'Hendra Gunawan',
    phone: '0818-0912-3344',
    email: 'hendra.gunawan@techindo.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    district: 'Jakarta Barat (Puri Indah)',
    tier: 'Regular',
    totalOrders: 16,
    totalSpent: 8300000,
    lastOrderDate: '2026-08-30',
    favoriteCategories: ['Home & Living', 'Elektronik & Gadget'],
    favoriteStores: ['IKEA Alam Sutera'],
    csatRating: 4.8,
    paymentPreference: 'Bank Transfer',
  },
  {
    id: 'cst-05',
    name: 'Ratna Juwita Sari',
    phone: '0852-3344-5566',
    email: 'ratna.catering@yahoo.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    district: 'Jakarta Pusat (Menteng)',
    tier: 'VIP',
    totalOrders: 42,
    totalSpent: 21300000,
    lastOrderDate: '2026-09-01',
    favoriteCategories: ['Kuliner & Snack Tradisional'],
    favoriteStores: ['Pasar Senen Kue Subuh'],
    csatRating: 5.0,
    paymentPreference: 'QRIS',
  },
  {
    id: 'cst-06',
    name: 'Fajar Nugraha',
    phone: '0813-7766-5544',
    email: 'fajar.nug@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    district: 'Jakarta Timur (Rawamangun)',
    tier: 'New',
    totalOrders: 3,
    totalSpent: 1250000,
    lastOrderDate: '2026-09-01',
    favoriteCategories: ['Fashion & Sepatu'],
    favoriteStores: ['Pasar Baru'],
    csatRating: 4.7,
    paymentPreference: 'COD',
  },
];

// ─── 4. ORDERS DATA ──────────────────────────────────────────────
export const INITIAL_ORDERS: JastipOrder[] = [
  {
    id: 'ord-8929',
    invoiceNumber: 'INV-JST-20260901-001',
    createdAt: '2026-09-01T09:15:00+07:00',
    customerName: 'Siti Rahmawati, S.E.',
    customerPhone: '0812-9988-1122',
    deliveryAddress: 'Jl. Senopati No. 42, Kebayoran Baru',
    district: 'Jakarta Selatan',
    storeName: 'Pasar Tanah Abang (Blok A)',
    storeCategory: 'Fashion & Tekstil Grosir',
    driverId: 'drv-01',
    driverName: 'Budi Santoso',
    driverAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    status: 'shopping',
    paymentStatus: 'paid',
    items: [
      {
        id: 'itm-101',
        name: 'Gamis Rayon Crinkle Sage Green (Size L)',
        category: 'Fashion',
        quantity: 3,
        unit: 'pcs',
        estimatedPrice: 120000,
        actualPrice: 115000,
        jastipFee: 25000,
        status: 'purchased',
        storeName: 'Toko Berkah Mode Blok A',
      },
      {
        id: 'itm-102',
        name: 'Jilbab Paris Voal Premium (Dusty Rose & Mauve)',
        category: 'Fashion',
        quantity: 5,
        unit: 'pcs',
        estimatedPrice: 35000,
        actualPrice: 32000,
        jastipFee: 10000,
        status: 'purchased',
        storeName: 'Hijab Corner Blok B',
      },
    ],
    totalGoodsCost: 505000,
    totalJastipFee: 125000,
    shippingFee: 25000,
    totalAmount: 655000,
    depositPaid: 655000,
    outstandingAmount: 0,
    verificationTimeMins: 8,
    shoppingTimeMins: 28,
    packingTimeMins: 0,
    deliveryTimeMins: 0,
    totalCycleTimeMins: 36,
    targetSLATimeMins: 120,
    isOnTime: true,
    notes: 'Tolong carikan bahan yang adem dan tidak menerawang ya mas.',
  },
  {
    id: 'ord-8928',
    invoiceNumber: 'INV-JST-20260901-002',
    createdAt: '2026-09-01T08:45:00+07:00',
    customerName: 'dr. Maya Anggraini',
    customerPhone: '0811-2233-4455',
    deliveryAddress: 'Cluster Green Cove Blok C5 No 12, BSD City',
    district: 'Tangerang Selatan',
    storeName: 'IKEA Alam Sutera',
    storeCategory: 'Home & Living',
    driverId: 'drv-03',
    driverName: 'Ahmad Fauzi',
    driverAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'shopping',
    paymentStatus: 'dp',
    items: [
      {
        id: 'itm-103',
        name: 'Raskog Trolley Putih',
        category: 'Home Living',
        quantity: 1,
        unit: 'unit',
        estimatedPrice: 699000,
        actualPrice: 699000,
        jastipFee: 65000,
        status: 'purchased',
        storeName: 'IKEA Alam Sutera Lantai 1',
      },
      {
        id: 'itm-104',
        name: 'Swedish Meatball Frozen 1kg',
        category: 'Food',
        quantity: 2,
        unit: 'pack',
        estimatedPrice: 165000,
        actualPrice: 165000,
        jastipFee: 25000,
        status: 'purchased',
        storeName: 'IKEA Swedish Food Market',
      },
    ],
    totalGoodsCost: 1029000,
    totalJastipFee: 115000,
    shippingFee: 45000,
    totalAmount: 1189000,
    depositPaid: 600000,
    outstandingAmount: 589000,
    verificationTimeMins: 12,
    shoppingTimeMins: 42,
    packingTimeMins: 0,
    deliveryTimeMins: 0,
    totalCycleTimeMins: 54,
    targetSLATimeMins: 150,
    isOnTime: true,
    notes: 'Pakai cooler box ya untuk meatball agar tetap beku sampai BSD.',
  },
  {
    id: 'ord-8927',
    invoiceNumber: 'INV-JST-20260901-003',
    createdAt: '2026-09-01T08:00:00+07:00',
    customerName: 'Dewi Lestari',
    customerPhone: '0813-8899-7711',
    deliveryAddress: 'Apartemen Sudirman Tower A Lt. 18',
    district: 'Jakarta Pusat',
    storeName: 'Grand Indonesia (Sephora)',
    storeCategory: 'Beauty & Luxury Retail',
    driverId: 'drv-02',
    driverName: 'Rian Pratama',
    driverAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    status: 'delivering',
    paymentStatus: 'paid',
    items: [
      {
        id: 'itm-105',
        name: 'Rare Beauty Soft Pinch Liquid Blush (Shade Hope)',
        category: 'Beauty',
        quantity: 1,
        unit: 'pcs',
        estimatedPrice: 430000,
        actualPrice: 430000,
        jastipFee: 45000,
        status: 'purchased',
        storeName: 'Sephora Grand Indonesia',
      },
      {
        id: 'itm-106',
        name: 'Zara Red Vanilla EDT 100ml',
        category: 'Beauty',
        quantity: 1,
        unit: 'bottle',
        estimatedPrice: 299000,
        actualPrice: 299000,
        jastipFee: 35000,
        status: 'purchased',
        storeName: 'Zara Grand Indonesia',
      },
    ],
    totalGoodsCost: 729000,
    totalJastipFee: 80000,
    shippingFee: 20000,
    totalAmount: 829000,
    depositPaid: 829000,
    outstandingAmount: 0,
    verificationTimeMins: 5,
    shoppingTimeMins: 32,
    packingTimeMins: 10,
    deliveryTimeMins: 18,
    totalCycleTimeMins: 65,
    targetSLATimeMins: 100,
    isOnTime: true,
    notes: 'Mohon minta tester parfum kalau tersedia di kasir ya kak.',
  },
  {
    id: 'ord-8926',
    invoiceNumber: 'INV-JST-20260901-004',
    createdAt: '2026-09-01T06:30:00+07:00',
    completedAt: '2026-09-01T08:15:00+07:00',
    customerName: 'Ratna Juwita Sari',
    customerPhone: '0852-3344-5566',
    deliveryAddress: 'Jl. Teuku Umar No. 12, Menteng',
    district: 'Jakarta Pusat',
    storeName: 'Pasar Senen Kue Subuh',
    storeCategory: 'Kuliner & Snack Tradisional',
    driverId: 'drv-05',
    driverName: 'Eko Wahyudi',
    driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'delivered',
    paymentStatus: 'paid',
    items: [
      {
        id: 'itm-107',
        name: 'Lemper Ayam Spesial Daun Pisang',
        category: 'Food',
        quantity: 50,
        unit: 'pcs',
        estimatedPrice: 3500,
        actualPrice: 3500,
        jastipFee: 500,
        status: 'purchased',
        storeName: 'Kios Kue Bu Hj. Marwah',
      },
      {
        id: 'itm-108',
        name: 'Pastel Ragout Ayam Telur',
        category: 'Food',
        quantity: 50,
        unit: 'pcs',
        estimatedPrice: 4000,
        actualPrice: 4000,
        jastipFee: 500,
        status: 'purchased',
        storeName: 'Kios Kue Bu Hj. Marwah',
      },
    ],
    totalGoodsCost: 375000,
    totalJastipFee: 50000,
    shippingFee: 25000,
    totalAmount: 450000,
    depositPaid: 450000,
    outstandingAmount: 0,
    verificationTimeMins: 5,
    shoppingTimeMins: 22,
    packingTimeMins: 15,
    deliveryTimeMins: 20,
    totalCycleTimeMins: 62,
    targetSLATimeMins: 90,
    isOnTime: true,
    notes: 'Untuk acara arisan jam 9 pagi, wajib fresh dan masih hangat.',
  },
  {
    id: 'ord-8925',
    invoiceNumber: 'INV-JST-20260901-005',
    createdAt: '2026-09-01T09:40:00+07:00',
    customerName: 'Amanda Putri Maharani',
    customerPhone: '0817-5544-3322',
    deliveryAddress: 'Jl. Fatmawati Golf No. 8, Cilandak',
    district: 'Jakarta Selatan',
    storeName: 'Pasar Mayestik',
    storeCategory: 'Kain & Crafting',
    driverId: 'drv-01',
    driverName: 'Budi Santoso',
    driverAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    status: 'pending',
    paymentStatus: 'pending_receipt',
    items: [
      {
        id: 'itm-109',
        name: 'Kain Brokat Semi Prancis Warna Lavender (3 Meter)',
        category: 'Fashion',
        quantity: 3,
        unit: 'meter',
        estimatedPrice: 185000,
        jastipFee: 30000,
        status: 'pending',
        storeName: 'Fancy Textile Mayestik',
      },
    ],
    totalGoodsCost: 555000,
    totalJastipFee: 90000,
    shippingFee: 25000,
    totalAmount: 670000,
    depositPaid: 300000,
    outstandingAmount: 370000,
    verificationTimeMins: 4,
    shoppingTimeMins: 0,
    packingTimeMins: 0,
    deliveryTimeMins: 0,
    totalCycleTimeMins: 4,
    targetSLATimeMins: 120,
    isOnTime: true,
    notes: 'Pastikan warnanya lavender soft bukan ungu tua ya.',
  },
  {
    id: 'ord-8924',
    invoiceNumber: 'INV-JST-20260901-006',
    createdAt: '2026-09-01T07:15:00+07:00',
    completedAt: '2026-09-01T09:10:00+07:00',
    customerName: 'Hendra Gunawan',
    customerPhone: '0818-0912-3344',
    deliveryAddress: 'Perumahan Puri Indah Blok B7/14',
    district: 'Jakarta Barat',
    storeName: 'Sentra Kuliner & Oleh-oleh Bandung',
    storeCategory: 'Kuliner & Oleh-oleh Daerah',
    driverId: 'drv-05',
    driverName: 'Eko Wahyudi',
    driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'delivered',
    paymentStatus: 'paid',
    items: [
      {
        id: 'itm-110',
        name: 'Kartika Sari Pisang Bollen Keju (2 Box)',
        category: 'Food',
        quantity: 2,
        unit: 'box',
        estimatedPrice: 78000,
        actualPrice: 78000,
        jastipFee: 20000,
        status: 'purchased',
        storeName: 'Kartika Sari Drop Point',
      },
      {
        id: 'itm-111',
        name: 'Prima Rasa Brownies Panggang Almond',
        category: 'Food',
        quantity: 1,
        unit: 'box',
        estimatedPrice: 92000,
        actualPrice: 92000,
        jastipFee: 20000,
        status: 'purchased',
        storeName: 'Prima Rasa Outlet',
      },
    ],
    totalGoodsCost: 248000,
    totalJastipFee: 60000,
    shippingFee: 30000,
    totalAmount: 338000,
    depositPaid: 338000,
    outstandingAmount: 0,
    verificationTimeMins: 6,
    shoppingTimeMins: 35,
    packingTimeMins: 10,
    deliveryTimeMins: 30,
    totalCycleTimeMins: 81,
    targetSLATimeMins: 120,
    isOnTime: true,
  },
  {
    id: 'ord-8923',
    invoiceNumber: 'INV-JST-20260901-007',
    createdAt: '2026-09-01T09:50:00+07:00',
    customerName: 'Fajar Nugraha',
    customerPhone: '0813-7766-5544',
    deliveryAddress: 'Jl. Pemuda No. 88, Rawamangun',
    district: 'Jakarta Timur',
    storeName: 'Pasar Baru',
    storeCategory: 'Fashion & Sepatu',
    driverId: 'drv-04',
    driverName: 'Dimas Wicaksono',
    driverAvatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80',
    status: 'issue',
    paymentStatus: 'cod',
    items: [
      {
        id: 'itm-112',
        name: 'Sepatu Kulit Oxford Brown (Size 42)',
        category: 'Fashion',
        quantity: 1,
        unit: 'pasang',
        estimatedPrice: 380000,
        actualPrice: 450000,
        jastipFee: 40000,
        status: 'replaced',
        storeName: 'Toko Sepatu Sinar Jaya Pasar Baru',
        note: 'Harga toko naik dari estimasi awal, perlu konfirmasi persetujuan customer',
      },
    ],
    totalGoodsCost: 450000,
    totalJastipFee: 40000,
    shippingFee: 25000,
    totalAmount: 515000,
    depositPaid: 0,
    outstandingAmount: 515000,
    verificationTimeMins: 10,
    shoppingTimeMins: 25,
    packingTimeMins: 0,
    deliveryTimeMins: 0,
    totalCycleTimeMins: 35,
    targetSLATimeMins: 90,
    isOnTime: true,
    notes: 'Perbedaan harga Rp 70.000, driver sedang menunggu konfirmasi via WhatsApp.',
  },
];

// ─── 5. TIME & SLA BREAKDOWN STATS ─────────────────────────────────
export const TIME_SLA_STAGES: TimeSLABreakdown[] = [
  {
    stage: '1. Verifikasi Order & Budget',
    targetMins: 10,
    actualMins: 7.5,
    status: 'optimal',
    description: 'Pengecekan ketersediaan kuota belanja, verifikasi DP, dan instruksi item.',
  },
  {
    stage: '2. Belanja di Lokasi / Toko',
    targetMins: 45,
    actualMins: 36.2,
    status: 'optimal',
    description: 'Waktu personal shopper mencari barang, antri kasir, dan validasi struk.',
  },
  {
    stage: '3. Sortir & Packing Khusus',
    targetMins: 15,
    actualMins: 12.0,
    status: 'optimal',
    description: 'Pemberian bubble wrap, fragile label, atau ice gel untuk kuliner.',
  },
  {
    stage: '4. Delivery ke Customer',
    targetMins: 35,
    actualMins: 27.8,
    status: 'optimal',
    description: 'Perjalanan kurir mengantar barang dari toko/hub ke alamat tujuan.',
  },
];

// ─── 6. HOURLY ORDER PATTERNS (JAM SIBUK) ───────────────────────────
export const HOURLY_PATTERNS: HourlyOrderPattern[] = [
  { hour: '07:00', ordersCount: 14, gmv: 4200000, isPeak: false },
  { hour: '08:00', ordersCount: 28, gmv: 8900000, isPeak: true },
  { hour: '09:00', ordersCount: 36, gmv: 12400000, isPeak: true },
  { hour: '10:00', ordersCount: 42, gmv: 15100000, isPeak: true },
  { hour: '11:00', ordersCount: 38, gmv: 13800000, isPeak: true },
  { hour: '12:00', ordersCount: 31, gmv: 9800000, isPeak: false },
  { hour: '13:00', ordersCount: 29, gmv: 9100000, isPeak: false },
  { hour: '14:00', ordersCount: 34, gmv: 11200000, isPeak: false },
  { hour: '15:00', ordersCount: 45, gmv: 16800000, isPeak: true },
  { hour: '16:00', ordersCount: 48, gmv: 18200000, isPeak: true },
  { hour: '17:00', ordersCount: 40, gmv: 14600000, isPeak: true },
  { hour: '18:00', ordersCount: 26, gmv: 8400000, isPeak: false },
  { hour: '19:00', ordersCount: 18, gmv: 5900000, isPeak: false },
  { hour: '20:00', ordersCount: 10, gmv: 3100000, isPeak: false },
];

// ─── 7. CATEGORY DISTRIBUTION DATA ────────────────────────────────
export const CATEGORY_DISTRIBUTION = [
  { name: 'Fashion & Tekstil Grosir', value: 38, revenue: 64200000, color: '#6366f1' },
  { name: 'Home & Living (IKEA/Ace)', value: 24, revenue: 48900000, color: '#06b6d4' },
  { name: 'Beauty & Skincare Mall', value: 16, revenue: 39500000, color: '#ec4899' },
  { name: 'Kuliner & Snack Daerah', value: 14, revenue: 31800000, color: '#f59e0b' },
  { name: 'Kain & Kerajinan Craft', value: 8, revenue: 22400000, color: '#10b981' },
];

// ─── 8. 7-DAYS FINANCIAL & OPERATIONAL TREND ───────────────────────
export const DAILY_TREND_DATA = [
  { day: 'Senin (26/08)', gmv: 18400000, jastipFee: 3120000, orders: 48, onTimeRate: 97.5 },
  { day: 'Selasa (27/08)', gmv: 21500000, jastipFee: 3680000, orders: 54, onTimeRate: 98.1 },
  { day: 'Rabu (28/08)', gmv: 19800000, jastipFee: 3340000, orders: 50, onTimeRate: 96.0 },
  { day: 'Kamis (29/08)', gmv: 24200000, jastipFee: 4150000, orders: 62, onTimeRate: 95.8 },
  { day: 'Jumat (30/08)', gmv: 31600000, jastipFee: 5420000, orders: 78, onTimeRate: 94.9 },
  { day: 'Sabtu (31/08)', gmv: 38900000, jastipFee: 6850000, orders: 94, onTimeRate: 96.8 },
  { day: 'Minggu (01/09)', gmv: 42100000, jastipFee: 7410000, orders: 102, onTimeRate: 97.2 },
];

// ─── 9. FINANCIAL OVERVIEW HELPER ─────────────────────────────────
export function getFinancialOverview(): FinancialOverview {
  return {
    totalGMV: 196500000,
    totalJastipFee: 33970000,
    totalShippingRevenue: 12400000,
    netRevenue: 33970000 + 12400000,
    netMarginPercentage: 17.3,
    activeTalanganCash: 6980000, // Uang kas operasional yang sedang di lapangan
    unsettledInvoicesCount: 14,
    unsettledAmount: 3850000,
    settledTodayAmount: 18450000,
  };
}

// ─── 10. FORMATTERS ───────────────────────────────────────────────
export function formatIDR(amount: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatCompactIDR(amount: number): string {
  if (amount >= 1_000_000_000) return `Rp ${(amount / 1_000_000_000).toFixed(1)} Milyar`;
  if (amount >= 1_000_000) return `Rp ${(amount / 1_000_000).toFixed(1)} Jt`;
  if (amount >= 1_000) return `Rp ${(amount / 1_000).toFixed(0)} Rb`;
  return `Rp ${amount}`;
}
